### ISSUE TITLE
Improve Pharo reference on website

### ISSUE THREAD

**Issue by seandenigris** [guillep/DBXTalk#6]
In http://guillep.github.io/DBXTalk/garage/ change "Pharo language" to "Pharo environment" or just
Pharo, and link to http://pharo.org/

**Comment by guillep** [comment]
Fixed in https://github.com/guillep/DBXTalk/commit/3c45cddaabef21e9e2113ae93b8a7c7e084910ea. I chose to put just Pharo.

**Comment by seandenigris** [comment]
Thx :)
